[project]
name = "face-blockchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yosuf20", email = "jyosuf6@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "insightface>=1.0.1",
    "opencv-python>=5.0.0.93",
]

[project.scripts]
face-blockchain = "face_blockchain:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
